// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrP3FUsDYiS1eqpGy91JqD3TG2E9Esoc',
    appId: '1:461739170377:android:0241975ff014cfc2993d98',
    messagingSenderId: '461739170377',
    projectId: 'sayeer-coop',
    storageBucket: 'sayeer-coop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIAiIpyaeg38L6DBOmYBvVnfXReCux1Y8',
    appId: '1:461739170377:ios:32062fd2f323f539993d98',
    messagingSenderId: '461739170377',
    projectId: 'sayeer-coop',
    storageBucket: 'sayeer-coop.firebasestorage.app',
    iosBundleId: 'com.example.sayerCoop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hyE45BePtGKYXgcIKeTOBP9EbZM6MR0',
    appId: '1:461739170377:web:81bb93d523edb154993d98',
    messagingSenderId: '461739170377',
    projectId: 'sayeer-coop',
    authDomain: 'sayeer-coop.firebaseapp.com',
    storageBucket: 'sayeer-coop.firebasestorage.app',
    measurementId: 'G-3G9GBLE958',
  );

}